/*
 * XMLParserTest.java
 *
 * Created on March 15, 2002, 12:53 PM
 */

package ca.uhn.hl7v2.parser;

import junit.framework.TestCase;
import ca.uhn.hl7v2.HL7Exception;
import org.w3c.dom.Document;
import ca.uhn.hl7v2.model.Message;
import ca.uhn.hl7v2.model.Segment;
import ca.uhn.hl7v2.model.Type;
import ca.uhn.hl7v2.model.v21.segment.MSH;

/**
 * JUnit test harness for XMLParser
 * @author Bryan Tripp
 */
public class XMLParserTest extends TestCase {

    XMLParser parser;
    
    /** Creates a new instance of XMLParserTest */
    public XMLParserTest(String arg) {
        super(arg);
    }
    
    public void setUp() throws Exception {
        parser = new DummyXMLParser();
    }
    
    public void tearDown() throws Exception {
        
    }
    
    public void testGetAckID() throws HL7Exception {
        assertEquals(parser.getAckID("<MSA.2>12</MSA.2>"), "12");
        assertEquals(parser.getAckID("<thing<foo> help >>><msa.2> *** </i forget"), "***");
        String ackID = parser.getAckID("<there is no msa.2>x</msa.2>");
        assertEquals(null, ackID);
        ackID = parser.getAckID("<msa.2>x");
        assertEquals(null, ackID);
        ackID = parser.getAckID("<MSA.2>   12   \r</MSA.2>");
        assertEquals("12", ackID);
        ackID = parser.getAckID("<?xml version=\"1.0\" standalone=\"no\"?><!DOCTYPE RSP_K22 SYSTEM \"http://localhost/DTDs/Q22Response.dtd\"><RSP_K22><MSH><MSH.1>|</MSH.1><MSH.2>^~/&amp;</MSH.2><MSH.3><HD.1>MPI</HD.1><HD.3>ISO</HD.3></MSH.3><MSH.4><HD.1>HealthLink</HD.1><HD.3>ISO</HD.3></MSH.4><MSH.5><HD.1>UHN Vista</HD.1><HD.3>ISO</HD.3></MSH.5><MSH.6><HD.1>UHN</HD.1><HD.3>ISO</HD.3></MSH.6><MSH.7>200204292049</MSH.7><MSH.9><CM_MSG_TYPE.1>RSP</CM_MSG_TYPE.1><CM_MSG_TYPE.2>K22</CM_MSG_TYPE.2><CM_MSG_TYPE.3>RSP_K22</CM_MSG_TYPE.3></MSH.9><MSH.10>200204292049100799</MSH.10><MSH.11><PT.1>P</PT.1></MSH.11><MSH.12><VID.1>2.4</VID.1></MSH.12><MSH.21>Q22</MSH.21></MSH><MSA><MSA.1>AA</MSA.1><MSA.2>876</MSA.2></MSA><QAK><QAK.2>OK</QAK.2><QAK.3><CE.1>Q22</CE.1><CE.2>");
        assertEquals("876", ackID);
    }
    
 
    public void testGetEncoding() throws Exception {
        String test1 = "<MSH>\r<MSH.1>|</MSH.1>\r<MSH.2>^~\\&amp;</MSH.2>\r</MSH>";
        String test2 = "<MSH>\r<MSH.1>|</MSH.1>\r<MSH.2>^~\\&amp;</MSH.2>\r";  //bad: no </MSH>
        assertEquals("XML", parser.getEncoding(test1));
        assertEquals(null, parser.getEncoding(test2));
    }
    
    /*public void testParse() throws Exception {
        String test1 = "<MSH>\r<MSH.1>|</MSH.1>\r<MSH.2>^~\\&amp;</MSH.2>\r</MSH>";
        Message m = parser.parse(test1);
        assertEquals(null, m);
    }*/
    
    public void testGetVersion() throws Exception {
        String message = "<?xml version=\"1.0\"?> <!DOCTYPE QBP_Q22 SYSTEM \"http://142.224.24.144/QueryServices/xmlDtds/Q22Query.dtd\"> <!--Generated by XML Authority--><QBP_Q22>  <MSH>   <MSH.1>|</MSH.1>   <MSH.2>^~/&amp;</MSH.2>   <MSH.3>    <HD.1>UHN Vista</HD.1>    <HD.3>ISO</HD.3>   </MSH.3>   <MSH.4>    <HD.1>UHN</HD.1>    <HD.3>ISO</HD.3>   </MSH.4>   <MSH.5>    <HD.1>MPI</HD.1>    <HD.3>ISO</HD.3>   </MSH.5>   <MSH.6>    <HD.1>HealthLink</HD.1>    <HD.3>ISO</HD.3>   </MSH.6>   <MSH.7>20020429132718.734-0400</MSH.7>   <MSH.9>    <CM_MSG_TYPE.1>QBP</CM_MSG_TYPE.1>    <CM_MSG_TYPE.2>Q22</CM_MSG_TYPE.2>  <CM_MSG_TYPE.3>QBP_Q21</CM_MSG_TYPE.3>   </MSH.9>   <MSH.10>855</MSH.10>   <MSH.11>    <PT.1>P</PT.1>   </MSH.11>   <MSH.12>    <VID.1>2.4</VID.1>      </MSH.12>   <MSH.21>Q22</MSH.21>  </MSH>  <QPD>   <QPD.1>    <CE.1>Q22</CE.1>    <CE.2>Find Candidates</CE.2>    <CE.3>HL7nnnn</CE.3>   </QPD.1>   <QPD.3><QIP><QIP.1>@PID.3.1</QIP.1><QIP.2>9583518684</QIP.2></QIP><QIP><QIP.1>@PID.3.4.1</QIP.1><QIP.2>CANON</QIP.2></QIP><QIP><QIP.1>@PID.5.1.1</QIP.1><QIP.2>ECG-Acharya</QIP.2></QIP><QIP><QIP.1>@PID.5.2</QIP.1><QIP.2>Nf</QIP.2></QIP><QIP><QIP.1>@PID.5.7</QIP.1><QIP.2>L</QIP.2></QIP><QIP><QIP.1>@PID.7</QIP.1><QIP.2>197104010000</QIP.2></QIP><QIP><QIP.1>@PID.8</QIP.1><QIP.2>M</QIP.2></QIP></QPD.3>   <QPD.4>100</QPD.4>   <QPD.8><CX.4><HD.1>TTH</HD.1></CX.4></QPD.8>  <QPD.9>13831</QPD.9><QPD.10>ULTIuser2</QPD.10><QPD.11>234564</QPD.11><QPD.12>R&amp;H Med</QPD.12></QPD>  <RCP>   <RCP.1>I</RCP.1>   <RCP.2><CQ.1>100</CQ.1><CQ.2>RD</CQ.2></RCP.2>   <RCP.3>   <CE.1>R</CE.1>   </RCP.3>  </RCP> </QBP_Q22>";
        String ver = parser.getVersion(message);
        assertEquals("2.4", ver);
    }
    
    public void testRemoveWhitespace() throws Exception {
        assertEquals("hello", parser.removeWhitespace("\t\r\nhello "));
        assertEquals("hello there", parser.removeWhitespace(" hello \t \rthere\r\n"));
    }
    
    /**
     * -
     * @throws HL7Exception -
     */
    public void testGetCriticalResponseData() throws HL7Exception {
        
        String message = "<ORU_R01 xmlns=\"urn:hl7-org:v2xml\">\r\n" + 
                "    <MSH>\r\n" + 
                "        <MSH.1>|</MSH.1>\r\n" + 
                "        <MSH.2>^~\\&amp;</MSH.2>\r\n" + 
                "        <MSH.3>LABMI1</MSH.3>\r\n" + 
                "        <MSH.5>DMCRES</MSH.5>\r\n" + 
                "        <MSH.7>\r\n" + 
                "            <TS.1>19951010134000</TS.1>\r\n" + 
                "        </MSH.7>\r\n" + 
                "        <MSH.9>\r\n" + 
                "            <CM_MSG.1>ORU</CM_MSG.1>\r\n" + 
                "            <CM_MSG.2>R01</CM_MSG.2>\r\n" + 
                "        </MSH.9>\r\n" + 
                "        <MSH.10>LABMI1199510101340007</MSH.10>\r\n" + 
                "        <MSH.11>D</MSH.11>\r\n" + 
                "        <MSH.12>2.2</MSH.12>\r\n" + 
                "        <MSH.15>AL</MSH.15>\r\n" + 
                "    </MSH>";
        
        Segment data = parser.getCriticalResponseData(message);
        
        Type actual = data.getField(2, 0);
        String expected = "^~\\&";
        assertEquals(expected, actual.toString()); // Encoding
        
    }
    
        
    public class DummyXMLParser extends XMLParser {
        public DummyXMLParser() throws HL7Exception { 
            super();
        }
        
        public Message parseDocument(Document XMLMessage, String version) throws HL7Exception {
            return null;
        }
        
        public Document encodeDocument(Message source) throws HL7Exception {
            return null;
        }        
        
    }

}
